// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddffffffffffffffffffffffff
fffffffffffffffffdfffdddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.ffffffdddddddddfffffffffffffffffffffffff
fffffffffffffffffddddffddddddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddddffffffffffffffffffffffff
fffffffffffffffffddddddffddddddddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.ffffffdddddddddddddddddddddddffffffffffffffffffffffff
fffffffffffffffffddddddfffffddddddddddfdddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddfffddddddffffffffffffffffffffffff
fffffffffffffffffddddddddfddfffffddddddfffdddddddddffff.ffffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddffffddddddffffffffffffffffffffffff
fffffffffffffffffdddddddddfddddddfffddddddfddddddddddddfffff.fffddddddddddddddffffffffffffffffdddddddddddddddddddddddddddddddfffdddddfddffffffffffffffffffffffff
fffffffffffffffffdddddddddffddddddddfffddddffffdddddddddddddffffffddddddddddffffffffffffddddddddddddddddddddddddddddddddddfffffdddddffddffffffffffffffffffffffff
fffffffffffffffffddddddddddffddddddddddfffdddddffffffffffffffffdddddddddffddddddddddddddddddddddddddddddddddddddddddddddff.ffddddddfddddffffffffffffffffffffffff
fffffffffffffffffddddddddddfdfffddddddddddffdddddddddddddddddddfffdddddddffddddddffdddddddddddddddddddddddddddddddddddff..fddddddffdddfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfddddfffdddddddddffffddddddddddddddddddddddddddfffddddddffffffffdddddddddddddddddddddddddff..ffddddfffdddddfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddffdddddddddddffffffdddddddddddddddddfdff.ffffdddddddddddfffffffffffffffffffffffffddffdddddfddddddddfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddffffdddddddddddddfffffffffffffdddfdddffdddfffddfddddddddddddddddddddddddddddddddfdddddffdddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddffffddddddddddddddddddddddddfdddfdffdddddfddfffddddddddddddddddddddddddddddfdddfffdddddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddddffffffddddddddddffdddfffddddfddffddddddddddffddddddddddddddddddddddddffdddffdddddddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddddddddddffffffffffdddfffddddddfdffffdddddddddddffddddddddddddddddddffffdddffdddddddddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddddddddddddddddddddddddddddddddfddddfffdddddddddddfffddfffffffffffffdddffffdddddddddddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddddddddddddddddddddddddddddddddfdddddddffddddddddddddffddddddddddddddffdddddddddddddddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddddddddddddddddddddddddddddddddfdddddddddfffddddddddddddddddddddddfffdddddddddddddddddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddddddddddddddddddddddddddddddddfddddddddddddffffddddddddddddddffffddddddddddddddddddddddddfdffffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddffffffffffffffddddddddddddddddddddddddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfddddddddddddddddddddddddddddddddddddddddddd2dfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddddddddddddddddddddddddddd2222dfdddddddddddddddddddddddddddddddddddddddddddddddddddd22ddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddd2d22222dddddddddddddddddddddddddd2dddddfddddddddddddddddddddddddddddddddddddddddddddddddddd22dddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfddddddd22ddd22222dddddddddddd2222222222ddddddfdddddddddddddddddddddddddddddddddddddddddddd2222222dddddddfdfdffffffffffffffffffffffff
fffffffffffffffffddddddfdddfdddddddddddddddd2222ddd2dddd22dddddddddddddddfddddddddddddddddddddddddddddddddddddddddddd22dddddddddddddfdfdffffffffffffffffffffffff
ffffffffffffffffffdddddfdddfddddddddddddddddddd222222222dddddddddddddddddfddd2dddddddddddddddddddddddddddddddddd222222dddddddddddddfddfdffffffffffffffffffffffff
ffffffffffffffffffdddddfdddfdddddddddddddddddddddddddddddddddddddddddddddfdddd2ddddddddddddddddddddddddddddddd222ddddddddddddddddddfdfddffffffffffffffffffffffff
ffffffffffffffffffdddddfdddfdddddddddddddddddddddddddddddddddddddddddddddfddddd2d222dddd22dddddddddddddd222222dddddddddddddddddddddfdfddffffffffffffffffffffffff
ffffffffffffffffffddddfddddfdddddddddddddddddddddddddddddddddddddddd22dddfdddddd2dd22222d22222dddddddd22dddddddddddddddddddddddddddfdfddffffffffffffffffffffffff
ffffffffffffffffffddddfddddfdddddddddddddddddddddddddddddddddddd22222ddddfdddddddddddddddddddd2ddddd222ddddddddddddddddddddddddddddfdfddffffffffffffffffffffffff
ffffffffffffffffffddddfddddfdddddddd2dddddddddddddddddddddddddd2dddddddddfddddddddddddddddddddd22d22dddddddddddddddddddddddddddddddfdfddffffffffffffffffffffffff
ffffffffffffffffffddddfddddfdddddddd22222dddddddddddd2222222222ddddddddddfddddddddddddddddddddddd2ddddddddddddddddddddddd22ddddddddfdfddffffffffffffffffffffffff
ffffffffffffffffffddddfddddfdddddddddddd222222dd22222ddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddd22dddddddddfdfddffffffffffffffffffffffff
ffffffffffffffffffddddfddddfdddddddddddddddddd222ddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddd222ddddddddddfdfddffffffffffffffffffffffff
ffffffffffffffffffddddfddddfdddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddd222dddddddddddddfdfddffffffffffffffffffffffff
ffffffffffffffffffddddfddddfdddddddddddddddddddddddddddddddddddddddddddddfdddd2ddddddddddddddddddddddddddddddddddd2dddddddddddddddfddfddffffffffffffffffffffffff
ffffffffffffffffffddddfddddfddddddd22ddddddddddddddddddddddddddddd222ddddfddddd22ddddd222222dddddddddddddddddd2222ddddddddddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfddddfdddddddd2ddddddddddddddddddddddd22ddd2dddddddfddddddd2dd22ddddd2222dddddd222222222ddddddddddddddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfddddfdddddddd2222222222dddddd22dd2222d22222dddddddfdddddddd22ddddddddddd222222dddddddddddddddddddddddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfddddfddddddddddddddddd2222222d222dddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfddddfdddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfddddfdddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfddddfdddddddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddd2dddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfddddfdddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddd22dddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfddddfdddddddddddddddddddddddddddddddddddddd2222dddfdddddddddddddddddddddddddddddddddddddddddddddd2dddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfdddddfddddddddddddddddddddddddddddddddddd222ddddddfdddddd2ddddddddddddddddddddddddddddddddddddd222dddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfdddddfdddddddd2dddddddddddddddddddddddddd2ddddddddfddddddd222ddddddddddddddddddddd22222dddddd222dddddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfdddddfddddddd2222222ddddddddddddddddddd22dddddddddfddddddddd2222dddddddddddddddd222dddd22dd222dddddddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfdddddfdddddddddddddd22222222222222222222ddddddddddfddddddddddddd22222222222222222dddddddd222dddddddddddddddfddfddffffffffffffffffffffffff
fffffffffffffffffffdddfdddddfddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddfdfffffffffffffffffffffffff
fffffffffffffffffffddddfddddfddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddfdfffffffffffffffffffffffff
fffffffffffffffffffddddfddddfddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddd2ddddddddfddfdfffffffffffffffffffffffff
fffffffffffffffffffddddfddddfddddddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddd2dddddddddfdffdfffffffffffffffffffffffff
fffffffffffffffffffddddfddddfddddddd22dddddddddddddddddddddddddddd2ddddddfdddddd22ddddddddddddddddddddddddddddddddd222222dddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfdddddfddddddd22ddddddddddddddddddddddddd22dddddddfddddddd22ddddddddddddddddddddddddddddddd22ddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfdddddfdddddddd2222dddddddddddddddddddd222ddddddddfdddddddd22dddddddddddddddddddddddddddd222dddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfdddddfdddddddddddd2222222222dddd222222dddddddddddfddddddddd2222ddddddddddddddddddddd22222dddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfdddddfdddddddddddddddddddddd2222dddddddddddddddddfddddddddddddd22222222222222222dd22d22dddddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfdddddfdddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddd222ddddddddddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfdddddfdddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfddddddfdddddd22dd222222dddddddd2222dddddddddddd2dfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfddddddfddddddd2222dddd22dddd222dddd222dd2222222ddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfddddddfddddddddddddddddd22222ddddddddd222ddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfddddddfddddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddd22ddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffddddfddddddfddddddddddddddddddddddddddddddddddddddddddfdddddddd2dddddddddddddd222dddddddddddddddddddddd22d2ddddfdfddfffffffffffffffffffffffff
ffffffffffffffffffffdddfddddddfdddddddddddddddddddddddddddddddddd2222ddddfddddddddd2ddddddddd2222ddd222dddddddddddddddddd2ddddddddfdfddfffffffffffffffffffffffff
ffffffffffffffffffffdddfddddddfdddddddddddd22222ddddddddddddddd222dd222ddfdddddddddd2ddddd222dddddddddd222ddd2222222222222ddddddddfdfddfffffffffffffffffffffffff
ffffffffffffffffffffdddfddddddfddddddd22d222ddd222dddddddddd222ddddddd2ddfddddddddddd22dd2dddddddddddddddd222dddddddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffffdfdddddddfdddddddd222ddddddd22222222222dddddddddddddfddddddddddddd22dddddddddddddddddddddddddddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffffdfddddddffdddddddddddddddddddddd22ddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfddfffffffffffffffffffffffff
fffffffffffffffffffffffdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff1ff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff1ffff11ffffffffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff1ffffff11fffffffff111ff1ffffffffffffffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffff
fffffffffffffff1ffffffff1ffffff11fffff1ffffffffffffff111f11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffff1ffff
ffffffffffffffff1ffffff1ffffff1ffffffff1ffffffffffff1ffffff11fffffffffffffffffff1fffffffffffffffffffffff11111111fffffffff1fffffffffffffffffffffffffffffffff1ffff
ffffffffffffffff1fffff1fffffff1fffffffff1ffffffffff1fffffffff11fffffffffffffffff1fffffffffffffff11111111fffffff1fffffffff1fffffffffffffffffffffffffffffffff1ffff
ffffffffffffffff1ffff11ffffff1fffffffffff1ffffffff1ffffffffffff1ffffffffffffffff1ffffffffffffff1fffffffffffffff1fffffffff1fffffffffffffffffff1ffffffff1ffff1ffff
ffffffffffffffff1fff11fffffff1fffffffffff1ffffffff1ffffffffffff1ffffffffffffffff1ffffffffffffff1fffffffffffffff1fffffffff1ffffffff11fffffffff1ffffffff1ffff1ffff
ffffffffffffffff11111fffffffff1fffffffff1ffffffff1fffffffffffff11fffffffffffffff1fffffffffffff1fffffffffffffff11fffffffff1ffffff11ff1ffffffff1ffffffff1ffff1ffff
ffffffffffffffff11ffffffffffff1fffffff11ffffffffff1ffffffffffff11fffffffffffffff1ffffffffffff11fffffffffffffff11fffffffff1ffff11fffff1fffffff1fffffffff1fff1ffff
ffffffffffffffff1f1ffffffffff111111111ffffffffffff1fffffffffffff1fffffffffffffff1ffffffffffff11fffffffffffffff11fffffffff1ffff1fffffff1ffffff1fffffffff1fff1ffff
ffffffffffffffff1ff1fffffffffff1fffffffffffffffff11fffffffffffff1fffffffffffffff1ffffffffffff1ffffffffffffffff11fffffffff1ffff11fffffff1fffff1ffffffff1ffff1ffff
ffffffffffffffff1fff1fffffffffff1fffffffffffffff1f1fffffffffffff11ffffffffffffff1ffffffffffff1ffffffffffffffff1f1ffffffff1ffff1fffffffff1ffff1ffffffff1ffff1ffff
ffffffffffffffff1ffff1ffffffffff11ffffffffffffff1f1ffffffffffffff1ffffffffff11111fffffffffffff1ffffffffffffff1ff1ffffffff1ffff1ffffffffff1ffff1ffffff11ffff1ffff
ffffffffffffffff1fffff1fffffffffff11fffffffffffff1fffffffffffffff11ffffffff1ffff1fffffffffffff1ffffffffffffff1ff1ffffffff1ffff1fffffffffff1ffff1ffff111ffff1ffff
ffffffffffffffff1fffff1fffffffffffff11fffffffffff111ffffffffffff1f1fffffff1fffff1fffffffffffff1ffffffffffffff1ff1ffffffff1ffff1ffffffffff1ffffff1111ff1ffff1ffff
ffffffffffffffff1ffffff1ffffffffffffffffffffffffffff1111111fffff1ff1fffffff1ffff1ffffffffffffff1fffffffffffff1fff1fffffff1ffff1ffffffffff1fffffffffff1ff11111fff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffff1ffffff1ffff1ffffffffffffff1fffffffffff11ffff1fffffff1ffff1ffffffffff1fffffffffff1f1ffff1fff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffff1fff1fffffffffffffff111111111111ffffff1fffffff1ffff1ffffffffff1fffffffffff1f1ffff1fff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffff11ff1ffffffffffffffffffffffffffffffffff1ffffff1ffff1fffffffff1ffffffffffffff1ffff1fff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffff11fffffffffffffffffffffffffffffffffff1ffffff1ffff1fffffffff1ffffffffffffff1fff1ffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffff1ffffff1fffff11111ffff1ffffffffffffff1fff1ffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffff11fff11ffffffffffffffffffffff1ffffff1ffffffffff11111fffffffffffffff11f1ffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffffffffffffff111f1f1fffffffffffffffffffffff1fffff1ffffffffffffffffffffffffffffffff1fffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffff1ff111ff1fffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffff1111ffff1ffff1fff1ffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffff1fff1ffff1ffff1fff1ffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffff1ffff1ffff1ffff1ffff1fffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffff1ffff1ffff1ffff1ffff1fffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffff11ff1ffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image2":return img`
....................
....................
....................
....................
....................
....................
....................
.....26d7bf.........
.....6d7bfb.........
.....d7bfb7.........
.....7bfb7d.........
.....bfb7d6.........
.....fb7d62.........
....................
....................
....................
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "anim1":return [img`
....................
....................
....................
....................
....................
....................
....................
.....26d7bf.........
.....6d7bfb.........
.....d7bfb7.........
.....7bfb7d.........
.....bfb7d6.........
.....fb7d62.........
....................
....................
....................
....................
....................
....................
....................
`, img`
....................
....................
....................
....................
....................
....................
....................
.....26d7bf.........
.....6d7bfb.........
.....d7bfb7.........
.....7bfb7d.........
.....bfb7d6.........
.....fb7d62.........
....................
....................
....................
....................
....................
....................
....................
`, img`
....................
....................
....................
....................
....................
....................
....................
.....26d7bf.........
.....6d7bfb.........
.....d7bfb7.........
.....7bfb7d.........
.....bfb7d6.........
.....fb7d62.........
....................
....................
....................
....................
....................
....................
....................
`, img`
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
`, img`
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
`, img`
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
`, img`
....................
....................
....................
....................
....................
....................
....................
.....26d7bf.........
.....6d7bfb.........
.....d7bfb7.........
.....7bfb7d.........
.....bfb7d6.........
.....fb7d62.........
....................
....................
....................
....................
....................
....................
....................
`, img`
....................
....................
....................
....................
....................
....................
....................
.....26d7bf.........
.....6d7bfb.........
.....d7bfb7.........
.....7bfb7d.........
.....bfb7d6.........
.....fb7d62.........
....................
....................
....................
....................
....................
....................
....................
`, img`
....................
....................
....................
....................
....................
....................
....................
.....26d7bf.........
.....6d7bfb.........
.....d7bfb7.........
.....7bfb7d.........
.....bfb7d6.........
.....fb7d62.........
....................
....................
....................
....................
....................
....................
....................
`];
            case "anim2":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
